-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 11:17:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ANIMAL_WELFARE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ANIMAL_WELFARE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ANIMAL_WELFARE` DEFAULT CHARACTER SET utf8 ;
USE `ANIMAL_WELFARE` ;

-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`VeterinaryHospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`VeterinaryHospital` (
  `hospitalId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `bedCount` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`hospitalId`),
  UNIQUE INDEX `hospitalId_UNIQUE` (`hospitalId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Guardian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Guardian` (
  `guardianId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`guardianId`),
  UNIQUE INDEX `guardianId_UNIQUE` (`guardianId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Animal` (
  `animalId` INT NOT NULL AUTO_INCREMENT,
  `species` VARCHAR(45) NULL,
  `breed` VARCHAR(45) NULL,
  `neutered` VARCHAR(45) NULL,
  `hospitalId` INT NOT NULL,
  `guardianId` INT NOT NULL,
  PRIMARY KEY (`animalId`),
  INDEX `fk_Animal_VeterinaryClinic1_idx` (`hospitalId` ASC) VISIBLE,
  INDEX `fk_Animal_Gaurdian1_idx` (`guardianId` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_VeterinaryClinic1`
    FOREIGN KEY (`hospitalId`)
    REFERENCES `ANIMAL_WELFARE`.`VeterinaryHospital` (`hospitalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Gaurdian1`
    FOREIGN KEY (`guardianId`)
    REFERENCES `ANIMAL_WELFARE`.`Guardian` (`guardianId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Medicines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Medicines` (
  `medicineId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `sideEffects` VARCHAR(45) NULL,
  `timeperiod(days)` INT NULL,
  PRIMARY KEY (`medicineId`),
  UNIQUE INDEX `medicineId_UNIQUE` (`medicineId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Doctor` (
  `doctorId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `qualification` VARCHAR(45) NULL,
  `specialization` VARCHAR(45) NULL,
  `age` INT NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`doctorId`),
  UNIQUE INDEX `doctorId_UNIQUE` (`doctorId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`PetOwner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`PetOwner` (
  `guardianId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`guardianId`),
  INDEX `fk_PetOwner_Gaurdian1_idx` (`guardianId` ASC) VISIBLE,
  CONSTRAINT `fk_PetOwner_Gaurdian1`
    FOREIGN KEY (`guardianId`)
    REFERENCES `ANIMAL_WELFARE`.`Guardian` (`guardianId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Pharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Pharmacy` (
  `pharmacyId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`pharmacyId`),
  UNIQUE INDEX `pharmacyId_UNIQUE` (`pharmacyId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Consultation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Consultation` (
  `consultationId` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(45) NULL,
  `diagnosis` VARCHAR(45) NULL,
  `height` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `temperature` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `doctorId` INT NOT NULL,
  `hospitalId` INT NOT NULL,
  `animalId` INT NOT NULL,
  PRIMARY KEY (`consultationId`),
  INDEX `fk_Consultation_Doctor1_idx` (`doctorId` ASC) VISIBLE,
  INDEX `fk_Consultation_VeterinaryClinic1_idx` (`hospitalId` ASC) VISIBLE,
  INDEX `fk_Consultation_Animal1_idx` (`animalId` ASC) VISIBLE,
  UNIQUE INDEX `consultationId_UNIQUE` (`consultationId` ASC) VISIBLE,
  CONSTRAINT `fk_Consultation_Doctor1`
    FOREIGN KEY (`doctorId`)
    REFERENCES `ANIMAL_WELFARE`.`Doctor` (`doctorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultation_VeterinaryClinic1`
    FOREIGN KEY (`hospitalId`)
    REFERENCES `ANIMAL_WELFARE`.`VeterinaryHospital` (`hospitalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultation_Animal1`
    FOREIGN KEY (`animalId`)
    REFERENCES `ANIMAL_WELFARE`.`Animal` (`animalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Shelter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Shelter` (
  `guardianId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `capacity` INT NULL,
  `animalId` INT NOT NULL,
  PRIMARY KEY (`guardianId`),
  INDEX `fk_Shelter_Gaurdian1_idx` (`guardianId` ASC) VISIBLE,
  CONSTRAINT `fk_Shelter_Gaurdian1`
    FOREIGN KEY (`guardianId`)
    REFERENCES `ANIMAL_WELFARE`.`Guardian` (`guardianId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Driver` (
  `driverId` INT NOT NULL,
  `driverName` VARCHAR(45) NULL,
  `JoiningDate` DATETIME NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`driverId`),
  UNIQUE INDEX `driverId_UNIQUE` (`driverId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`EmergencyReport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`EmergencyReport` (
  `caseId` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NULL,
  `location` VARCHAR(45) NULL,
  `condition` VARCHAR(45) NULL,
  `vehicleNumber` VARCHAR(45) NULL,
  `driverId` INT NOT NULL,
  `hospitalId` INT NOT NULL,
  `reportedBy` VARCHAR(45) NULL,
  `reportedAt` DATETIME NULL,
  PRIMARY KEY (`caseId`),
  INDEX `fk_Rescue_Driver_idx` (`driverId` ASC) VISIBLE,
  INDEX `fk_Rescue_VeterinaryClinic1_idx` (`hospitalId` ASC) VISIBLE,
  UNIQUE INDEX `caseId_UNIQUE` (`caseId` ASC) VISIBLE,
  CONSTRAINT `fk_Rescue_Driver`
    FOREIGN KEY (`driverId`)
    REFERENCES `ANIMAL_WELFARE`.`Driver` (`driverId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rescue_VeterinaryClinic1`
    FOREIGN KEY (`hospitalId`)
    REFERENCES `ANIMAL_WELFARE`.`VeterinaryHospital` (`hospitalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`PharmacyBilling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`PharmacyBilling` (
  `billingId` INT NOT NULL AUTO_INCREMENT,
  `paymentStatus` VARCHAR(45) NULL,
  `paymentType` VARCHAR(45) NULL,
  `paymentDate` DATE NULL,
  `amount($)` INT NULL,
  `Pharmacy_pharmacyId` INT NOT NULL,
  PRIMARY KEY (`billingId`),
  INDEX `fk_PharmacyBilling_Pharmacy1_idx` (`Pharmacy_pharmacyId` ASC) VISIBLE,
  UNIQUE INDEX `billingId_UNIQUE` (`billingId` ASC) VISIBLE,
  CONSTRAINT `fk_PharmacyBilling_Pharmacy1`
    FOREIGN KEY (`Pharmacy_pharmacyId`)
    REFERENCES `ANIMAL_WELFARE`.`Pharmacy` (`pharmacyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Prescription` (
  `medicineId` INT NOT NULL,
  `consultationId` INT NOT NULL,
  `billingId` INT NOT NULL,
  `Dosage` INT NULL,
  `timePeriod(Days)` VARCHAR(45) NULL,
  INDEX `fk_Prescription_Medication1_idx` (`medicineId` ASC) VISIBLE,
  INDEX `fk_Prescription_Consultation1_idx` (`consultationId` ASC) VISIBLE,
  INDEX `fk_Prescription_Billing1_idx` (`billingId` ASC) VISIBLE,
  UNIQUE INDEX `consultationId_UNIQUE` (`consultationId` ASC) VISIBLE,
  CONSTRAINT `fk_Prescription_Medication1`
    FOREIGN KEY (`medicineId`)
    REFERENCES `ANIMAL_WELFARE`.`Medicines` (`medicineId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Consultation1`
    FOREIGN KEY (`consultationId`)
    REFERENCES `ANIMAL_WELFARE`.`Consultation` (`consultationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Billing1`
    FOREIGN KEY (`billingId`)
    REFERENCES `ANIMAL_WELFARE`.`PharmacyBilling` (`billingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Stock` (
  `medicineId` INT NOT NULL,
  `pharmacyId` INT NOT NULL,
  `Quantity` INT NULL,
  INDEX `fk_Stock_Medication1_idx` (`medicineId` ASC) VISIBLE,
  INDEX `fk_Stock_Pharmacy1_idx` (`pharmacyId` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Medication1`
    FOREIGN KEY (`medicineId`)
    REFERENCES `ANIMAL_WELFARE`.`Medicines` (`medicineId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_Pharmacy1`
    FOREIGN KEY (`pharmacyId`)
    REFERENCES `ANIMAL_WELFARE`.`Pharmacy` (`pharmacyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`HospitalBilling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`HospitalBilling` (
  `hospitalBillingId` INT NOT NULL,
  `service` VARCHAR(45) NULL,
  `amount($)` INT NULL,
  `paymentStatus` VARCHAR(45) NULL,
  `paymentType` VARCHAR(45) NULL,
  `paymentDate` VARCHAR(45) NULL,
  `hospitalId` INT NOT NULL,
  PRIMARY KEY (`hospitalBillingId`),
  INDEX `fk_HospitalBilling_VeterinaryHospital1_idx` (`hospitalId` ASC) VISIBLE,
  UNIQUE INDEX `hospitalBillingId_UNIQUE` (`hospitalBillingId` ASC) VISIBLE,
  CONSTRAINT `fk_HospitalBilling_VeterinaryHospital1`
    FOREIGN KEY (`hospitalId`)
    REFERENCES `ANIMAL_WELFARE`.`VeterinaryHospital` (`hospitalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMAL_WELFARE`.`Pharmacy_of_VeterinaryHospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL_WELFARE`.`Pharmacy_of_VeterinaryHospital` (
  `pharmacyId` INT NOT NULL,
  `hospitalId` INT NOT NULL,
  PRIMARY KEY (`pharmacyId`, `hospitalId`),
  INDEX `fk_Pharmacy_has_VeterinaryHospital_VeterinaryHospital1_idx` (`hospitalId` ASC) VISIBLE,
  INDEX `fk_Pharmacy_has_VeterinaryHospital_Pharmacy1_idx` (`pharmacyId` ASC) VISIBLE,
  UNIQUE INDEX `pharmacyId_UNIQUE` (`pharmacyId` ASC) VISIBLE,
  CONSTRAINT `fk_Pharmacy_has_VeterinaryHospital_Pharmacy1`
    FOREIGN KEY (`pharmacyId`)
    REFERENCES `ANIMAL_WELFARE`.`Pharmacy` (`pharmacyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pharmacy_has_VeterinaryHospital_VeterinaryHospital1`
    FOREIGN KEY (`hospitalId`)
    REFERENCES `ANIMAL_WELFARE`.`VeterinaryHospital` (`hospitalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
